### ISSUE TITLE
Screen corruption on Atom

### ISSUE THREAD

**Issue by mattmacy** [FreeBSDDesktop/freebsd-base-graphics#6] opened 2016-05-25 21:05 UTC
It's a dmesg after kldloading the latest. 

[drm] Initialized drm 1.1.0 20060810 
bus_register unimplemented!!! 
[drm:drm_pci_init] 
[drm:0xffffffff82dc525as] _ERROR_ FreeBSD needs DRIVER_MODESET 

System doesn't hang now, but it's still scfb which runs video. 

```
int drm_pci_init(struct drm_driver *driver, struct pci_driver *pdriver)
{
    struct pci_dev *pdev = NULL;
    const struct pci_device_id *pid;
    int i;

    DRM_DEBUG("\n");

    /* FreeBSD specific hackery */
    pdriver->busname = "vgapci";
    pdriver->bsdclass = &drm_devclass;
    pdriver->name = "drmn";

    if (driver->driver_features & DRIVER_MODESET)
        return pci_register_driver(pdriver);

    DRM_ERROR("FreeBSD needs DRIVER_MODESET");
    return (-ENOTSUP);

#ifdef __linux__    
    /* If not using KMS, fall back to stealth mode manual scanning. */
    INIT_LIST_HEAD(&driver->legacy_dev_list);
    for (i = 0; pdriver->id_table[i].vendor != 0; i++) {
        pid = &pdriver->id_table[i];

        /* Loop around setting up a DRM device for each PCI device
         * matching our ID and device class.  If we had the internal
         * function that pci_get_subsys and pci_get_class used, we'd
         * be able to just pass pid in instead of doing a two-stage
         * thing.
         */
        pdev = NULL;
        while ((pdev =
            pci_get_subsys(pid->vendor, pid->device, pid->subvendor,
                       pid->subdevice, pdev)) != NULL) {
            if ((pdev->class & pid->class_mask) != pid->class)
                continue;

            /* stealth mode requires a manual probe */
            pci_dev_get(pdev);
            drm_get_pci_dev(pdev, pid, driver);
        }
    }
    return 0;
#endif

```

The DRIVER_MODESET flag is getting cleared. It's unclear why this is happening or how it's tied to its inability to find a PCH.

**Comment by mishurov** [comment] 2016-05-26 08:40
Unfortunately, I have no time to tinker the code at this point: I have some personal stuff to do. During these two weeks, I have the access to the machine with Celeron N2840, 0x0f31. I'll try to be in touch in order to compile and to test, on demand, the forthcoming commits.

**Comment by mattmacy** [comment] 2016-05-28 06:34
Understood. Update whenever you get a chance to try the latest.

**Comment by mishurov** [comment] 2016-05-29 21:04
Commit: 34475b8ae1cd07d07e0e367296680157940f1307
The driver loads, I've attached dmesg.txt. An X starts, there're some strange colours and glitches in a urxvt-256color and at some point the kernel crashes, I've attached kgdb.txt

[kgdb.txt](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/288544/kgdb.txt)
[dmesg.txt](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/288545/dmesg.txt)

**Comment by mattmacy** [comment] 2016-05-29 21:06
re-enable debug logging. > 10s post-attach, prior to starting X set dev.drm.drm_debug=-1

**Comment by mattmacy** [comment] 2016-05-29 21:07
Actually. The problem is pretty obvious __get_user_pages isn't properly implemented. Thanks for the update. This is progress nonetheless.

**Comment by mattmacy** [comment] 2016-05-29 21:09
Fatal trap 12: page fault while in kernel mode
cpuid = 0; apic id = 00
fault virtual address   = 0x65
fault code      = supervisor read data, page not present
instruction pointer = 0x20:0xffffffff82e34016
stack pointer           = 0x28:0xfffffe02312db1c0
frame pointer           = 0x28:0xfffffe02312db200
code segment        = base 0x0, limit 0xfffff, type 0x1b
            = DPL 0, pres 1, long 1, def32 0, gran 1
processor eflags    = interrupt enabled, resume, IOPL = 3
current process     = 1174 (Xorg)
trap number     = 12

cpuid = 0
KDB: stack backtrace:
db_trace_self_wrapper() at db_trace_self_wrapper+0x2b/frame 0xfffffe02312dad50
vpanic() at vpanic+0x182/frame 0xfffffe02312dadd0
panic() at panic+0x43/frame 0xfffffe02312dae30
trap_fatal() at trap_fatal+0x351/frame 0xfffffe02312dae90
trap_pfault() at trap_pfault+0x1fd/frame 0xfffffe02312daef0
trap() at trap+0x4bf/frame 0xfffffe02312db100
calltrap() at calltrap+0x8/frame 0xfffffe02312db100
--- trap 0xc, rip = 0xffffffff82e34016, rsp = 0xfffffe02312db1d0, rbp = 0xfffffe02312db200 ---
__get_user_pages_fast() at __get_user_pages_fast+0xb6/frame 0xfffffe02312db200
i915_gem_userptr_get_pages() at i915_gem_userptr_get_pages+0xfd/frame 0xfffffe02312db240
i915_gem_object_get_pages() at i915_gem_object_get_pages+0x78/frame 0xfffffe02312db280
i915_gem_object_do_pin() at i915_gem_object_do_pin+0x645/frame 0xfffffe02312db330
i915_gem_execbuffer_reserve_vma() at i915_gem_execbuffer_reserve_vma+0x9c/frame 0xfffffe02312db370
i915_gem_execbuffer_reserve() at i915_gem_execbuffer_reserve+0x489/frame 0xfffffe02312db3e0
i915_gem_do_execbuffer() at i915_gem_do_execbuffer+0x8d7/frame 0xfffffe02312db730
i915_gem_execbuffer2() at i915_gem_execbuffer2+0x140/frame 0xfffffe02312db770
drm_ioctl() at drm_ioctl+0x272/frame 0xfffffe02312db870
linux_dev_ioctl() at linux_dev_ioctl+0x10e/frame 0xfffffe02312db940
devfs_ioctl_f() at devfs_ioctl_f+0x15d/frame 0xfffffe02312db9a0
kern_ioctl() at kern_ioctl+0x230/frame 0xfffffe02312dba00
sys_ioctl() at sys_ioctl+0x17e/frame 0xfffffe02312dbae0
amd64_syscall() at amd64_syscall+0x2db/frame 0xfffffe02312dbbf0
Xfast_syscall() at Xfast_syscall+0xfb/frame 0xfffffe02312dbbf0
--- syscall (54, FreeBSD ELF64, sys_ioctl), rip = 0x8024d170a, rsp = 0x7fffffffdaa8, rbp = 0x7fffffffdb60 ---
Uptime: 2m14s
Dumping 526 out of 8037 MB: (CTRL-C to abort) ..4%..13%..22%..31%..43%..52%..61%..73%..83%..92%

**Comment by mattmacy** [comment] 2016-05-30 07:19
Why don't you have line numbers for modules?

**Comment by mattmacy** [comment] 2016-05-30 07:46
I made a fairly dumb mistake in __get_user_pages_fast, the following change should fix it:

https://github.com/FreeBSDDesktop/freebsd-base-graphics/commit/04c512a5be57f63d16ad3d50cae8f358abe7ec55

**Comment by mishurov** [comment] 2016-05-30 09:14
It crashes the instant I start the X. The previous file without line numbers is a copy-paste from a kgdb. Sometimes FreeBSD doesn't save a backtrace in a text file, I have to run a dump within the debugger. 
[core.txt](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/289238/core.txt)
[messages.txt](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/289237/messages.txt)

**Comment by mattmacy** [comment] 2016-05-30 16:41
Thanks for the update.

**Comment by mattmacy** [comment] 2016-05-30 18:12
That path has never been hit before ...
https://github.com/FreeBSDDesktop/freebsd-base-graphics/commit/cf85e460605d15408b3a312e555a404e84fb3d3b

Please try again

**Comment by mishurov** [comment] 2016-05-30 21:41
After I installed the latest binary xf86-video-intel, the problem is gone, thereby I can't tell whether the problem is fixed by the commit or not. However, the result of the latest commit is the same as of the previous: the X starts, although a picture in Firefox goes distorted and after a some time the kernel crashes.
[core.txt](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/290098/core.txt)

**Comment by mattmacy** [comment] 2016-05-30 21:50
Another dumb bug :-/

Fixed by:
https://github.com/FreeBSDDesktop/freebsd-base-graphics/commit/14511ef38e16b373a62c108f4abf0392284aca8f

**Comment by mattmacy** [comment] 2016-05-30 21:50
Please retry.

**Comment by mishurov** [comment] 2016-05-31 06:55
The kernel doesn't crash now, although a picture is still distorted in various parts of the screen. I don't know how to debug this.
![screenshot_2016-05-31_09-49-46](https://cloud.githubusercontent.com/assets/1371641/15665793/bfe709ee-2715-11e6-9643-270bf0cc6e06.png)

**Comment by mattmacy** [comment] 2016-05-31 07:09
Hrrm. Distressing. Can you try sna? Just to see if it's any different?

**Comment by mattmacy** [comment] 2016-05-31 07:10
Or if you're using sna try uxa.

**Comment by mishurov** [comment] 2016-05-31 09:01
It wasn't set. After I set uxa, the result is the same as above. After I set sna, the X crashes the kernel at the moment I run a dmenu.
[core.txt](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/290673/core.txt)

**Comment by mattmacy** [comment] 2016-05-31 09:13
SNA seems to not have artifacts, but to be much more fragile. I'll fix this panic tomorrow.

**Comment by mattmacy** [comment] 2016-06-01 04:57
My last change should fix this panic https://github.com/FreeBSDDesktop/freebsd-base-graphics/commit/aa6c49d8c2a9c1a53925b336d855716e4d2004d0  

Could you please try again when you get the chance?

**Comment by mishurov** [comment] 2016-06-01 13:22
UXA is in the same state as before. SNA's panic is gone, but the picture is weird, there's a screenshot. These artifacts appear after some time.
![screenshot_2016-06-01_16-12-51](https://cloud.githubusercontent.com/assets/1371641/15711009/f4d4f544-2814-11e6-8ffc-ae355ae04eac.png)

**Comment by mishurov** [comment] 2016-06-02 12:34
I suppose that those artifacts are the result of the incorrect gem allocation due to porting the functions which use the Linux slab allocator to the FreeBSD kernel memory management. Whilst incorrect mutex locks or unlocks cause panic, these guys doesn't; therefore it's hard to debug the problem, for me it's hard also because I don't know the detailed structure of driver's functions. That's my back-seat driver opinion.

**Comment by mishurov** [comment] 2016-06-02 13:45
I've caught the bug. It doesn't crash kernel although breaks the X into a console and hangs. There's photo of the laptop screen, because it doesn't save any traceback afterwards.

And there's strange text about a relocation in two places from /var/log/messages

```
Jun  1 16:17:13 current kernel: [drm:i915_gem_check_execbuffer] UXA submitting garbage DR4, fixing up
Jun  1 16:17:13 current kernel: [drm:i915_gem_execbuffer_relocate] failed to relocate all vmas[drm:drm_ioctl] pid=100656, dev=0xe200, auth=1, DRM_IOCTL_GEM_CLOSE

Jun  2 16:16:04 current kernel: [drm:drm_ioctl] pid=100657, dev=0xe200, auth=1, I915_GEM_EXECBUFFER2
Jun  2 16:16:04 current kernel: [drm:i915_gem_execbuffer_relocate] failed to relocate all vmas[drm:drm_ioctl] pid=100657, dev=0xe200, auth=1, I915_GEM_BUSY
```

[messages.txt](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/295721/messages.txt)
![img_20160602_162308](https://cloud.githubusercontent.com/assets/1371641/15746923/1e884612-28e1-11e6-83ea-61d4af8cd2ae.jpg)

**Comment by mishurov** [comment] 2016-06-07 14:26
I'm off the grid at least for a month.

**Comment by Juanitou** [comment] 2016-06-13 16:09
I’m seeing the artifacts too with a Bay Trail-M (Celeron N2830) with SNA enabled. With default Xorg configuration a YouTube video is either black or slowly spouting some images. It was just a quick test.

**Comment by mattmacy** [comment] 2016-06-20 22:54
I've figured this out. i915's "atomic" updates need to be actually atomic. Fix forthcoming today or tomorrow.

**Comment by mattmacy** [comment] 2016-06-21 18:01
Try now. Pass --disable-gpu-compositing to chrome and whatever the equivalent is on FF. That appears to crash chrome right now. As a gross workaround:

> su
> % chmod 600 /dev/dri/card0
> % exit
> chrome &
> su 
> % chmod 660 /dev/dri/card0
> % exit

**Comment by Juanitou** [comment] 2016-06-22 12:08
On Bay Trail-M, the latest version, ecd31fbda09436d5da5fde62d1ece53c49ab492a, regress with respect to 490ab4ec68529b8f56c568d6c04095ee681760e9: the GPU hangs when the window manager starts and all graphics operations greatly slow: dmesg says:

```
[drm] Initialized drm 1.1.0 20060810
drmn0: <drmn> on vgapci0
vgapci0: child drmn0 requested pci_enable_io
vgapci0: child drmn0 requested pci_enable_io
[drm] Memory usable by graphics device = 2048M
[drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[drm] Driver supports precise vblank timestamp query.
[drm] Connector VGA-1: get mode from tunables:
[drm]   - kern.vt.fb.modes.VGA-1
[drm]   - kern.vt.fb.default_mode
[drm] Connector HDMI-A-1: get mode from tunables:
[drm]   - kern.vt.fb.modes.HDMI-A-1
[drm]   - kern.vt.fb.default_mode
[drm] Connector DP-1: get mode from tunables:
[drm]   - kern.vt.fb.modes.DP-1
[drm]   - kern.vt.fb.default_mode
[drm] Connector eDP-1: get mode from tunables:
[drm]   - kern.vt.fb.modes.eDP-1
[drm]   - kern.vt.fb.default_mode
[drm] Initialized i915 1.6.0 20160229 for drmn on minor 0
[drm] GMBUS [i915 gmbus vga] timed out, falling back to bit banging on pin 2
VT: Replacing driver "efifb" with new "fb".
start FB_INFO:
type=11 height=768 width=1366 depth=32
cmsize=16 size=4227072
pbase=0x80000000 vbase=0xffffffff81a10000
name=drmn0 flags=0x0 stride=5504 bpp=32
cmap[0]=0 cmap[1]=7f0000 cmap[2]=7f00 cmap[3]=c4a000
end FB_INFO
drmn0: fb0: inteldrmfb frame buffer device
[drm] stuck on render ring
[drm] GPU HANG: ecode 7:0:0xbb8ff7f8, reason: Ring hung, action: reset
[drm] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
[drm] Please file a _new_ bug report on bugs.freedesktop.org against DRI -> DRM/Intel
[drm] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
[drm] The gpu crash dump is required to analyze gpu hangs, so please always attach it.
[drm] GPU crash dump saved to /sys/class/drm/card0/error
drm/i915: Resetting chip after gpu hang
[drm] stuck on blitter ring
[drm] GPU HANG: ecode 7:1:0x96fbfff7, reason: Ring hung, action: reset
drm/i915: Resetting chip after gpu hang
```

Back to the old kernel and graphics speed resumes, but unusable because of artifacts.

**Comment by mattmacy** [comment] 2016-06-22 17:57
What window manager are you using? 
Are you using the X bits from the x-server-next branch? At a guess you're not. Please see the wiki.

**Comment by Juanitou** [comment] 2016-06-22 19:06
> What window manager are you using?

cwm

> Are you using the X bits from the x-server-next branch? At a guess you're not. Please see the wiki.

Yes and no, I installed the packages you provide at http://www.bsddesktop.com/images/xserver-next-pkgs/ but not compiled from source myself. I’ll try it and report back.

**Comment by mattmacy** [comment] 2016-06-22 19:07
Using the packages should be good enough. I'll try testing cwm here. twm of course works fine, but that's not much of a stretch.

**Comment by faelys** [comment] 2016-07-25 09:46
I'm not sure whether there was supposed to progress on this issue, but with the image `cftdisk_nodebug_2016062423.img.xz` can still get something like @mishurov 's screenshot on May 31st, when I use UXA acceleration.  (SNA has other, "healing", artifacts, and I can't play a youtube video).

I detailed that in [a post to `freebsd-x11@`](http://lists.freebsd.org/pipermail/freebsd-x11/2016-July/017759.html) and I can perform further testing if it helps.

**Closed as completed** 2017-02-14 03:29 UTC
Labels: bug

**Comment by faelys** [comment] 2017-02-14 07:02
May I object to the closing of this issue? I still occasionally get stuff like this:

![atom corruption](http://instinctive.eu/tmp/2017-02-14-intel-corruption.png)

The corruption frequency increases with the "age" of the X server, but just restarting X is enough to restart the clock.

I work around it by zooming, which seems make another "random draw" of whether I get a corrupted image or not. Here is an example of the same image without corruption:

![atom corruption worked around](http://instinctive.eu/tmp/2017-02-14-intel-corruption-fixed.png)

I couldn't reproduce this on the same hardware with a live Fedora.

EDIT: forgot to add that it's with the latest commit of the drm-next-4.7 branch, from 2016-12-26, and official CURRENT binary packages from around the end of January (before the libz update made it incompatible with drm-next-4.7).

**Comment by kev009** [comment] 2017-02-14 07:33
Retest with drm-next please (not drm-next-4.7)

**Comment by faelys** [comment] 2017-02-14 11:04
I've just started the cross-build (for some reason a local build doesn't work, it complains about missing `dev/hyperv/hyperv.h`). It might take a few days before being able to conclude either way.

I was using drm-next-4.7 instead of drm-next because last I heard it was still the branch recommended for intel users. Have things changed, or is it only to test the problem against the latest code?

**Comment by kev009** [comment] 2017-02-14 11:28
Yes, drm-next is now more stable and fixes most of the known issues.  You should use it with xorg-server 1.18+ and the modesetting driver.

**Comment by faelys** [comment] 2017-03-10 21:16
So using drm-next from about three weeks ago, I haven't been able to reproduce the corruption with the defaults settings, which I gather is UXA.

However I did a try with SNA, and there is massive corruption to the point of being unusable, but it doesn't look like anything posted here. Should I open a new ticket for that? Or is SNA known to be broken? What can I do to help diagnose it?
